### PR TITLE
removeRow and removeColumn

### PR DESCRIPTION
**Pull request by alexlehuynh**
Added functionality to the removeRow and removeColumn button.

### CODE REVIEW

**Review by choudhs2 — COMMENTED** [review]
Maybe add a case for when it was only 1 row/column so you decrement the other one too, Ie if cols==0 after removing then set rows = 0 and vice versa

**Comment by alexlehuynh** [comment]
Fixed for that edge case should work fine now :D

**Review by choudhs2 — COMMENTED** [review]
Perfect!

**Comment by wy33** [comment]
Works well!

**Pull request merged**
